version: '3.8'

services:
  app:
    build: .
    container_name: web3-indexer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - APP_DATABASE_DSN=host=db user=postgres password=mysecretpassword dbname=web3_indexer port=5432 sslmode=disable
      - APP_CHAIN_RPC_URL=${RPC_URL}
      - APP_SERVER_PORT=8080
    depends_on:
      - db # Wait for the database to start before launching the app

  # 2. database service
  db:
    image: postgres:15-alpine
    container_name: indexer-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=web3_indexer
    ports:
      - "5432:5432"
    # Persistent data mounting (to prevent data loss during Docker restart)
    volumes:
      - pg_data:/var/lib/postgresql/data

  # 1. Prometheus service
  prometheus:
    image: prom/prometheus:latest
    container_name: indexer-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  # 2. Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: indexer-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

# Define data volume
volumes:
  pg_data: